const emojiList = [
  /* 🏠 Dom */        "https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/svg/1f3e0.svg",
  /* 🏡 Dom z ogrodem */      "https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/svg/1f3e1.svg",
  /* 🏢 Biurowiec */          "https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/svg/1f3e2.svg",
  /* 🏣 Poczta japońska */    "https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/svg/1f3e3.svg",
  /* 🏤 Poczta europejska */  "https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/svg/1f3e4.svg",
  /* 🏥 Szpital */            "https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/svg/1f3e5.svg",
  /* 🏦 Bank */               "https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/svg/1f3e6.svg",
  /* 🏨 Hotel */              "https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/svg/1f3e8.svg",
  /* 🏩 Love hotel */         "https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/svg/1f3e9.svg",
  /* 🏪 Sklep nocny */        "https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/svg/1f3ea.svg",
  /* 🏫 Szkoła */             "https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/svg/1f3eb.svg",
  /* 🏬 Centrum handlowe */   "https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/svg/1f3ec.svg",
  /* 🏭 Fabryka */            "https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/svg/1f3ed.svg",
  /* 🏰 Zamek europejski */   "https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/svg/1f3f0.svg",
  /* 🏛️ Budynek klasyczny */ "https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/svg/1f3db.svg",
  /* 🏚️ Opuszczony dom */     "https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/svg/1f3da.svg",

  /* 🏟️ Stadion */                 "https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/svg/1f3df.svg",
  /* 🏗️ Dźwig budowlany */         "https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/svg/1f3d7.svg",
  /* 🏘️ Osiedle domków */          "https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/svg/1f3d8.svg",
  /* 🗼 Wieża (Tokyo Tower) */      "https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/svg/1f5fc.svg",
  /* 🎡 Diabelski młyn */           "https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/svg/1f3a1.svg",
  /* 🚂 Lokomotywa */               "https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/svg/1f682.svg",
  /* 🚓 Radiowóz policyjny */       "https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/svg/1f693.svg",
  /* 🚗 Samochód */                 "https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/svg/1f697.svg",
  /* ⛽ Stacja benzynowa */         "https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/svg/26fd.svg",
  /* ✈️ Samolot */                 "https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/svg/2708.svg",

  /* ⛪ Kościół */                  "https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/svg/26ea.svg",
  /* 🕍 Synagoga */                 "https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/svg/1f54d.svg",
  /* ⛴️ Prom/statki */             "https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/svg/26f4.svg",
  /* 🎬 Klaps filmowy */            "https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/svg/1f3ac.svg",
  /* 🚫 Zakaz wstępu */             "https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/svg/1f6ab.svg",
  /* 🔐 Zamek z kluczem */          "https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/svg/1f510.svg",
  /* 🪩 Kula dyskotekowa */         "https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/svg/1faa9.svg",

  /* ☠️ skull and crossbones */ "https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/svg/2620.svg",
  /* 👻 ghost */ "https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/svg/1f47b.svg",

/* red google pin */ "https://maps.gstatic.com/mapfiles/api-3/images/spotlight-poi2_hdpi.png",
/* blue pin */ "https://maps.gstatic.com/mapfiles/ms2/micons/blue-dot.png",
/* orange pin */ "https://maps.gstatic.com/mapfiles/ms2/micons/orange-dot.png"
/* ℹ️ information */ "https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/svg/2139.svg",
/* ❔ white question mark */ "https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/svg/2754.svg",
/* ❓ red question mark */ "https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/svg/2753.svg",
/* ❕ white exclamation */ "https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/svg/2755.svg",
/* ❗ red exclamation */ "https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/svg/2757.svg"
];
